# Generated by Django 4.2 on 2023-05-03 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gw', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gwfollowupgalaxy',
            name='catalog_objname',
            field=models.CharField(blank=True, default='', help_text='Name of this galaxy in the catalog', max_length=50, null=True),
        ),
    ]
