# Generated by Django 2.1.2 on 2019-01-26 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tom_targets', '0002_auto_20190115_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='redshift',
            field=models.FloatField(blank=True, help_text='The redshift of the target', null=True, verbose_name='Redshift'),
        ),
        migrations.AlterField(
            model_name='target',
            name='name2',
            field=models.CharField(blank=True, default='', help_text='An alternative name for this target', max_length=100, verbose_name='Name 2'),
        ),
        migrations.AlterField(
            model_name='target',
            name='name3',
            field=models.CharField(blank=True, default='', help_text='An alternative name for this target', max_length=100, verbose_name='Name 3'),
        ),
    ]
