# Generated by Django 2.1.2 on 2019-01-31 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tom_targets', '0003_auto_20190126_0131'),
        ('tom_targets', '0004_auto_20190123_2010'),
    ]

    operations = [
    ]
