# Generated by Django 2.1.2 on 2019-02-23 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tom_targets', '0005_auto_20190214_1722'),
        ('tom_targets', '0005_merge_20190131_1950'),
    ]

    operations = [
    ]
