# Generated by Django 3.1 on 2020-09-03 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_code', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScienceTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.TextField(default='', help_text='Science Tag', verbose_name='Science Tag')),
                ('userid', models.CharField(blank=True, default='', help_text='ID of user who created this tag', max_length=100, null=True, verbose_name='User ID')),
            ],
            options={
                'get_latest_by': ('id',),
            },
        ),
        migrations.AlterModelOptions(
            name='tnstarget',
            options={'get_latest_by': ('-name',), 'ordering': ('-id',)},
        ),
    ]
