# Generated by Django 3.1.1 on 2020-10-08 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_code', '0003_targettags'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReducedDatumExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(default='', help_text='Type of data (either photometry or spectroscopy)', max_length=100, verbose_name='Data Type')),
                ('key', models.CharField(default='', help_text='Keyword for information being stored', max_length=200, verbose_name='Key')),
                ('value', models.TextField(blank=True, default='', help_text='String value of the information being stored', verbose_name='Value')),
                ('float_value', models.FloatField(blank=True, help_text='Float value of the information being stored, if applicable', null=True, verbose_name='Float Value')),
                ('bool_value', models.BooleanField(blank=True, help_text='Boolean value of the information being stored, if applicable', null=True, verbose_name='Boolean Value')),
            ],
            options={
                'get_latest_by': 'id,',
            },
        ),
    ]
