# Generated by Django 3.1.3 on 2020-11-18 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tom_targets', '0018_auto_20200714_1832'),
        ('custom_code', '0004_reduceddatumextra'),
    ]

    operations = [
        migrations.AddField(
            model_name='reduceddatumextra',
            name='target',
            field=models.ForeignKey(default=27, on_delete=django.db.models.deletion.CASCADE, to='tom_targets.target'),
        ),
    ]
