# Generated by Django 3.1.3 on 2020-12-21 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tom_targets', '0018_auto_20200714_1832'),
        ('custom_code', '0005_reduceddatumextra_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reduceddatumextra',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tom_targets.target'),
        ),
        migrations.CreateModel(
            name='Papers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_first_name', models.CharField(default='', help_text='First name of the first author', max_length=20, verbose_name='First Author First Name')),
                ('author_last_name', models.CharField(default='', help_text='Last name of the first author', max_length=20, verbose_name='First Author Last Name')),
                ('description', models.TextField(default='', help_text='Brief description of the contents of the paper', null=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('in prep', 'In Prep'), ('submitted', 'Submitted'), ('published', 'Published')], max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tom_targets.target')),
            ],
            options={
                'get_latest_by': ('id',),
            },
        ),
    ]
