# Generated by Django 3.1.5 on 2022-04-05 19:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('custom_code', '0008_brokertarget'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokertarget',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='The time which this target was created in the TOM database.', verbose_name='Time Created'),
            preserve_default=False,
        ),
    ]
