# Generated by Django 3.2.16 on 2022-10-18 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_code', '0009_brokertarget_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='GladeCatalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pgc_no', models.IntegerField(blank=True, help_text='Principal Galaxies Catalog number', null=True, verbose_name='PGC number')),
                ('gwgc_name', models.CharField(blank=True, default='', help_text='Name in the GWGC catalog', max_length=100, null=True, verbose_name='GWGC name')),
                ('hyperleda_name', models.CharField(blank=True, default='', help_text='Name in the HyperLEDA catalog', max_length=100, null=True, verbose_name='HyperLEDA name')),
                ('twomass_name', models.CharField(blank=True, default='', help_text='Name in the 2MASS XSC catalog', max_length=100, null=True, verbose_name='2MASS name')),
                ('wisexscos_name', models.CharField(blank=True, default='', help_text='Name in the WISExSuperCOSMOS catalog', max_length=100, null=True, verbose_name='WISExSCOS name')),
                ('sdss_dr16q_name', models.CharField(blank=True, default='', help_text='Name in the SDSS-DR16Q catalog', max_length=100, null=True, verbose_name='SDSS-DR16Q name')),
                ('object_type_flag', models.CharField(blank=True, default='', help_text='Q: source is from SDSS-DR16Q catalog; G: source is from another catalog and has not been identified as a quasar', max_length=2, null=True, verbose_name='Object type flag')),
                ('ra', models.FloatField(help_text='Right Ascension, in degrees.', verbose_name='Right Ascension')),
                ('dec', models.FloatField(help_text='Declination, in degrees.', verbose_name='Declination')),
                ('mag', models.JSONField(blank=True, help_text='Magnitude information', null=True, verbose_name='Magnitudes')),
                ('z_helio', models.FloatField(blank=True, help_text='Heliocentric redshift', null=True)),
                ('z_cmb', models.FloatField(blank=True, help_text='CMB-frame redshift', null=True)),
                ('z_flag', models.IntegerField(blank=True, help_text='0: CMB frame redshift and lum distance values are not corrected for peculiar velocity; 1: they are corrected values', null=True)),
                ('v_err', models.FloatField(blank=True, help_text='Error of redshift from peculiar velocity estimation', null=True)),
                ('z_err', models.FloatField(blank=True, help_text='Measurement error of heliocentric redshift', null=True)),
                ('d_l', models.FloatField(blank=True, help_text='Luminosity distance, in Mpc', null=True, verbose_name='luminosity distance')),
                ('d_l_err', models.FloatField(blank=True, help_text='Error in luminosity distance, in Mpc', null=True, verbose_name='luminosity distance err')),
                ('dist_flag', models.IntegerField(blank=True, help_text='0: no measured redshift or distance; 1: distance from phot z; 2: redshift from lum dist; 3: distance from spec z', null=True, verbose_name='distance flag')),
                ('m_star', models.FloatField(blank=True, help_text='Stellar mass, in 10^10 M_solar', null=True)),
                ('m_star_err', models.FloatField(blank=True, help_text='Absolute error of stellar mass, in 10^10 M_solar', null=True)),
                ('m_star_flag', models.IntegerField(blank=True, help_text='0: M_star calculated assuming no active star formation; 1: M_star calculated assuming active star formation', null=True)),
                ('merger_rate', models.FloatField(blank=True, help_text='Log10 of estimated BNS merger rate in galaxy, in Gyr^-1', null=True)),
                ('merger_rate_err', models.FloatField(blank=True, help_text='Absolute error of estimated BNS merger rate in galaxy', null=True)),
            ],
        ),
    ]
