# Generated by Django 3.2.16 on 2023-04-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_code', '0010_gladecatalog'),
    ]

    operations = [
        migrations.CreateModel(
            name='NEDLVSCatalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', help_text='Preferred object name in NED', max_length=100, null=True, verbose_name='Preferred NED name')),
                ('ra', models.FloatField(help_text='Right Ascension, in degrees.', verbose_name='Right Ascension')),
                ('dec', models.FloatField(help_text='Declination, in degrees.', verbose_name='Declination')),
                ('object_type', models.CharField(blank=True, default='', help_text='Preferred object type in NED (see Table 1 in Cook et al.)', max_length=10, null=True, verbose_name='Object flag')),
                ('z', models.FloatField(blank=True, help_text='Heliocentric redshift', null=True)),
                ('z_err', models.FloatField(blank=True, help_text='Measurement error of heliocentric redshift', null=True)),
                ('z_tech', models.CharField(blank=True, default='', help_text='Technique used to measure redshift (SPEC, PHOT, UNKN, INFD, MOD, None or NULL)', max_length=10, null=True)),
                ('z_qual', models.BooleanField(blank=True, default=False, help_text='Qualifier flag indicating reliability of redshift (True=unreliable)', null=True, verbose_name='Redshift qualifier')),
                ('z_qual_flag', models.BooleanField(blank=True, default=False, help_text='Boolean flag indicating that the zqual flag has been updated in NED-LVS', null=True, verbose_name='Redshift qualifier flag')),
                ('z_refcode', models.CharField(blank=True, default='', help_text='Reference code for the publication that provided the redshift', max_length=20, null=True)),
                ('z_dist', models.FloatField(blank=True, help_text='Redshift-independent luminosity distance computed as the weighted average of measurements in either the primary or secondary indicators', null=True)),
                ('z_dist_err', models.FloatField(blank=True, help_text='Uncertainty in z_dist', null=True)),
                ('z_dist_method', models.CharField(blank=True, default='', help_text='Method used to measure the redshift-independent distance when a single method is used to compute the weighted average, otherwise "Wavg" when a mixture of methods are used (Cepheid, SNIa, TRGB, Wavg, etc.)', max_length=31, null=True)),
                ('z_dist_indicator', models.CharField(blank=True, default='', help_text='Measurement type indicator for redshift-independent distance (Primary or Secondary)', max_length=20, null=True)),
                ('z_dist_refcode', models.CharField(blank=True, default='', help_text='Reference code for the publication that provided the distance when a single measurement was chosen, otherwise "Mix" indicates an average of multiple measurements was used (refcode or Mix)', max_length=20, null=True)),
                ('d_l', models.FloatField(blank=True, help_text='Luminosity distance, in Mpc', null=True, verbose_name='luminosity distance')),
                ('d_l_err', models.FloatField(blank=True, help_text='Error in luminosity distance, in Mpc', null=True, verbose_name='luminosity distance err')),
                ('dist_method', models.CharField(blank=True, default='', help_text='Method used in the selected distance (Redshift or zIndependent)', max_length=31, null=True)),
                ('ebv', models.FloatField(blank=True, help_text='Foreground MW reddening E(B-V) from Schlafly & Finkbeiner (2011)', null=True, verbose_name='E(B-V)')),
                ('extinction', models.JSONField(blank=True, help_text='MW extinctions assuming Fitzpatrick et al. (1999)', null=True, verbose_name='Extinctions')),
                ('mag', models.JSONField(blank=True, help_text='Apparent magnitudes', null=True, verbose_name='Magnitudes')),
                ('lum', models.JSONField(blank=True, help_text='Monochromatic luminosities', null=True, verbose_name='Luminosities')),
                ('galex_phot', models.CharField(blank=True, default='', help_text='Flag indicating which catalog was used for GALEX photometry (ASC, MSC, z0MGS)', max_length=10, null=True)),
                ('tmass_phot', models.CharField(blank=True, default='', help_text='Flag indicating which catalog was used for 2MASS photometry (PSC, XSC, LGA)', max_length=10, null=True)),
                ('wise_phot', models.CharField(blank=True, default='', help_text='Flag indicating which catalog was used for WISE photometry (Pfit, APER, z0MGS)', max_length=10, null=True)),
                ('sfr', models.JSONField(blank=True, help_text='Star formation rate using either W4 luminosity scaling relation, or  FUV+W4 luminosity scaling relation (Section 2.4 of Cook et al.)', null=True, verbose_name='Star Formation Rates')),
                ('et_flag', models.BooleanField(blank=True, default=False, help_text='Boolean flag indicating an object is an early-type galaxy determined via IR or UV-IR colors (Section 4.3 of Cook et al.; True=colors indicate an early-type galaxy), and that the SFRs may be overestimated to varying degrees.', null=True)),
                ('m_star', models.FloatField(blank=True, help_text='Stellar mass using a W1 luminosity scaling relationship (Section 2.4 of Cook et al.)', null=True)),
                ('m_star_err', models.FloatField(blank=True, help_text='Uncertainty in m_star', null=True)),
                ('ml_ratio', models.FloatField(blank=True, help_text='The mass-to-light ratio used to calculate m_star (Section 2.4 of Cook et al.)', null=True)),
            ],
        ),
    ]
