# Generated by Django 3.2.16 on 2023-05-01 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_code', '0010_timeused'),
        ('custom_code', '0011_nedlvscatalog'),
    ]

    operations = [
    ]
